version: '3'

services:
  web:
    image: anroe/nginx-geoip2
    container_name: web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./geoip.mmdb:/etc/nginx/geoip.mmdb
    expose:
      - "80"
    restart: unless-stopped