version: "3"

services:
  searxng:
    container_name: searxng
    image: searxng/searxng
    expose:
      -  "8080"
    environment:
      - SEARXNG_PORT=8080
      - SEARXNG_URL=https://search.hostname.ltd
      - INSTANCE_NAME=Search
      - SEARXNG_REDIS_URL=redis://searxng-redis:6379/0
    volumes:
      - ./data/searxng:/etc/searxng
    depends_on:
      - searxng-redis
    networks:
      - searxng

  searxng-redis:
    container_name: searxng-redis
    image: redis:alpine
    command: redis-server --save "" --appendonly "no"
    networks:
      - searxng
    expose:
      - '6379'
    volumes:
      -  ./data/redis:/data

networks:
  searxng:
