version: '3'

services:
  apps-uptimekuma:
    image: louislam/uptime-kuma:latest
    container_name: apps-uptimekuma
    expose:
      - "3001"
    volumes:
      - ./data:/app/data
    restart: unless-stopped