version: '3.0' 

services:
  web-nginx-vanilla:
    container_name: web-nginx-vanilla
    image: nginx:latest
    volumes:
      - ./src:/usr/share/nginx/html:ro
    expose:
      - '80'
    restart: always