version: "2.1"

services:
  apps-vscode:
    image: codercom/code-server:latest
    user: "0" # Run as root ( good for installing packages and dependencies per instance )
    container_name: apps-vscode
    volumes:
      - ./config:/root/.config
      - ./user:/root/.local/share/code-server:rw
      - ./ssh:/root/.ssh # Set a static ssh config for every instance ( optional, but recommended )
      - ./gitconfig:/root/.gitconfig # Set a static gitconfig for every instance ( optional, but recommended )
      - /:/mnt/root:rshared # Share full host files ( optional and not recommended if shared between other users )
      - /var/run/docker.sock:/var/run/docker.sock # Share the Docker socket to allow Docker plugin to work with it ( optional )
    expose:
      - "8080"
    environment:
      - PUID=0
      - PGID=0
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "2"