version: "3"

services:
  wordpress-db:
    container_name: wordpress-db
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    expose:
      - 3306
    networks:
      - wordpress
   
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    volumes:
      - ./wp_data:/var/www/html
    expose:
      - 80
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=
      - WORDPRESS_DB_USER=
      - WORDPRESS_DB_PASSWORD=
      - WORDPRESS_DB_NAME=
    networks:
      - wordpress

  wordpress-phpmyadmin:
    container_name: wordpress-phpmyadmin
    image: phpmyadmin:latest
    expose:
      - 80
    restart: always
    networks:
      - wordpress
    environment:
      PMA_HOST: wordpress-db
      UPLOAD_LIMIT: 1G
    depends_on:
      - wordpress-db

networks:
  wordpress:
