version: "2"

services:
  server-adguard:
    image: adguard/adguardhome
    container_name: server-adguard
    expose:
      - 80
      - 443
      - 3000
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp #<-- Enable if wants to DNS-over-QUIC
      - 853:853/tcp #<-- Enable if wants to DNS-over-TLS
    volumes:
      - ./data/work:/opt/adguardhome/work
      - ./data/conf:/opt/adguardhome/conf
    restart: unless-stopped